config/routes.rb
Model::Application.routes.draw do
  resources :model_data do
    collection do
      get 'get_contents'
    end
  end
  
  resources :stages do
    collection do
      get 'get_contents'
    end
  end

  resources :dioramas do
    collection do
      post 'ready'
      post 'set_model'
      get 'get_model_datum'
      get 'get_stage'
      get 'get_diorama'
    end
  end

end

app/models/diorama.rb
class Diorama < ActiveRecord::Base
  has_one :stage
  has_many :model_transforms
  has_many :model_datum, :through => :model_transforms
  
  accepts_nested_attributes_for :model_transforms, allow_destroy: true
  accepts_nested_attributes_for :model_datum
end

app/controllers/dioramas_controller.rb
class DioramasController < ApplicationController
  before_action :set_diorama, only: [:show, :edit, :update, :destroy]
    
  DEF_STAGE_ID = 0
  DEF_MODEL_ID = 0

  # GET /dioramas
  # GET /dioramas.json
  def index
    @dioramas = Diorama.all
  end

  # GET /dioramas/1
  # GET /dioramas/1.json
  def show
    @stageTextures = @diorama.stage.textures[0]
    @selectedModel = @diorama.model_datum[0]
    @positions = @diorama.model_transforms.map do |model_transform|
      model_transform.transform unless model_transform.transform.nil?
    end
    
    @ids = @diorama.model_datum.map { |model_datum| model_datum.id }
    @modelData = @diorama.model_datum.map { |model_datum| model_datum.modeldata}
    @textures = @diorama.model_datum.map { |model_datum| model_datum.textures[0] }
  end

  # GET /dioramas/new
  def new
    @diorama = Diorama.new
    #@diorama.model_transforms.build

    # 素材配置のために格納しておく
    @model_data = ModelDatum.all
    @stages = Stage.all
    
    # 選択しているstageとmodeldataを入れる変数
    @selectedModel = ModelDatum.find(DEF_MODEL_ID)
    @selectedStage = Stage.find(DEF_STAGE_ID)
    @selectedModelTextures = @selectedModel.textures[0]
    @selectedStageTextures = @selectedStage.textures[0]
    
    # 初期値設定
    # セッションにデフォルトで使うstage_idを入れておいてcreateする時に使う
    session[:stage_id] = DEF_STAGE_ID
    session[:model_id] = DEF_MODEL_ID
  end

  # GET /dioramas/1/edit
  def edit
  end
  
  # JS側で指定されたIDのモデルデータをセットする
  def set_model
    @diorama = Diorama.new
    @model_data = ModelDatum.all
    @stages = Stage.all
    @selectedStage = Stage.find(DEF_STAGE_ID)
    @selectedModel = ModelDatum.find(params[:id])
    @selectedStageTextures = @selectedStage.textures[0]
    @selectedModelTextures = @selectedModel.textures[0]
    session[:stage_id] = DEF_STAGE_ID
    session[:model_id] = params[:id]

    render action: "new"
  end
  
  
  # POST /dioramas
  # POST /dioramas.json
  def create
    @diorama = Diorama.new(title: params[:diorama][:title])
    # Stage追加
    @diorama.stage = Stage.find(params[:diorama][:stage])
    
    # ModelTransforms追加
    tmp = params[:diorama][:model_transforms]
    objects = ActiveSupport::JSON.decode(tmp)
    objects.each do |obj|
      # convert array to string
      @transform = ModelTransform.new(transform: obj['pos'].to_s, model_datum: ModelDatum.find(obj['id']))
      @diorama.model_transforms << @transform
    end
    
    respond_to do |format|
      begin
        @diorama.save!
        format.html { redirect_to @diorama, notice: 'Diorama was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diorama }
      rescue ActiveRecord::RecordInvalid => e
        puts e
        format.html { render action: 'new' }
        format.json { render json: @diorama.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dioramas/1
  # PATCH/PUT /dioramas/1.json
  def update
    # ModelTransforms追加
    tmp = params[:diorama][:model_transforms]
    objects = ActiveSupport::JSON.decode(tmp)
    
    @diorama.model_transforms.clear
    transforms = objects.map do |obj|
      ModelTransform.new(transform: obj['pos'].to_s, model_datum: ModelDatum.find(obj['id']))
    end
    @diorama.model_transforms = transforms
    
    diorama_params = {
      title: params[:diorama][:title],
      #stage: Stage.find(params[:diorama][:stage]),
      #model_transforms: transforms
    }
    
    respond_to do |format|
      if @diorama.update_attributes(diorama_params)
        format.html { redirect_to @diorama, notice: 'Diorama was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diorama.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dioramas/1
  # DELETE /dioramas/1.json
  def destroy
    @diorama.destroy
    respond_to do |format|
      format.html { redirect_to dioramas_url }
      format.json { head :no_content }
    end
  end
  
  def get_model_datum
    model_datum = ModelDatum.find(params[:id])
    path = model_datum.textures[0] ? model_datum.textures[0].data.url : ""
    jsonString = { modelData: ActiveSupport::JSON.decode(model_datum.modeldata), texturePath: path }
    render json: jsonString
  end
  
  def get_stage
    stage = Stage.find(params[:id])
    path = stage.textures[0] ? stage.textures[0].data.url : ""
    jsonString = { stageData: ActiveSupport::JSON.decode(stage.scene_data), texturePath: path }
    render json: jsonString
  end
  
  def get_diorama
    diorama = Diorama.find(params[:id])
    jsonString = {
      modelData: diorama.model_datum.map { |m| ActiveSupport::JSON.decode(m.modeldata) },
      textures: diorama.model_datum.map { |m| m.textures[0] ? m.textures[0].data.url : "" },
      transforms: diorama.model_transforms.map {
        |t| ActiveSupport::JSON.decode(t.transform) unless t.transform.nil?
      },
      ids: diorama.model_datum.map { |m| m.id }
    }
    render json: jsonString
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diorama
      @diorama = Diorama.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diorama_params
      params.require(:diorama).permit(:title)
    end
end

app/helpers/dioramas_helper.rb
module DioramasHelper
end

app/views/dioramas/_form.html.erb
<%= form_for(@diorama) do |f| %>
  <% if @diorama.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diorama.errors.count, "error") %> prohibited this diorama from being saved:</h2>

      <ul>
      <% @diorama.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  	<%= f.label :stage %><br>
	<%= f.text_field :stage, :id => "stage_field", :value => DioramasController::DEF_STAGE_ID.to_s %>
  </div>
  
  <div class="field">
  	<%= f.label :model_transforms %><br>
		<%= f.text_field :model_transforms, :id => "transforms_field", :value => "" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dioramas/edit.html.erb
<h1>Editing diorama</h1>

<%= render 'form' %>

<%= link_to 'Show', @diorama %> |
<%= link_to 'Back', dioramas_path %>

app/views/dioramas/index.html.erb
<h1>Listing dioramas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dioramas.each do |diorama| %>
      <tr>
        <td><%= diorama.title %></td>
        <td><%= link_to 'Show', diorama %></td>
        <td><%= link_to 'Edit', edit_diorama_path(diorama) %></td>
        <td><%= link_to 'Destroy', diorama, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diorama', new_diorama_path %><br>
<%= link_to 'Index of Stage', stages_path %><br>
<%= link_to 'Index of ModelData', model_data_path %><br>

app/views/dioramas/new.html.erb
<%= stylesheet_link_tag "dioramas" %>
<h1>New diorama</h1>

<div id="siteBox">
	<%= render 'form' %>
	<%= link_to 'Back', dioramas_path %>
</div>

<div id="leftBox">
	<%= javascript_include_tag "stats.min", "gl-matrix.js", "styledstats", "dioramas", "toon", "dioramacontroller", "dioramaview", "main_creatediorama", "EditorControls", "TrackballControls" %>
</div> 

<div id="modelSelectionParent">
	<h2>ModelData:</h2>
	
	<div id="modelSelection">
		<% @model_data.each do |model_datum| %>
		  	<div class="item">
			    <%= model_datum.id %>
	  		</div>
		<% end %>
	</div>
</div>

<script type="x-shader/x-vertex" id="vs">
attribute vec4 color;
uniform   bool edge;
varying   vec3 vNormal;
varying   vec4 vColor;

void main(void){
    vec3 pos    = position;
    if(edge){
        pos    += normal * 0.05;
    }
    vNormal     = normal;
    vColor      = color;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
}
</script>

<script type="x-shader/x-fragment" id="fs">
precision mediump float;

uniform mat4      invMatrix;
uniform vec3      lightDirection;
uniform sampler2D texture;
uniform vec4      edgeColor;
varying vec3      vNormal;
varying vec4      vColor;

void main(void){
	if(edgeColor.a > 0.0){
	    gl_FragColor   = edgeColor;
	}else{
	    vec3  invLight = normalize(invMatrix * vec4(lightDirection, 0.0)).xyz;
	    float diffuse  = clamp(dot(vNormal, invLight), 0.0, 1.0);
	    vec4  smpColor = texture2D(texture, vec2(diffuse, 0.0));
	    gl_FragColor   = vColor * smpColor;
	}
}
</script>

app/views/dioramas/show.html.erb
<p id="notice"><%= notice %></p>

<div id="leftBox">
	<p>
	  <strong>Title:</strong>
	  <%= @diorama.title %>
	</p>
</div>

<div id="id"><%= @diorama.id %></div>
	
<%= javascript_include_tag "stats.min", "styledstats", "dioramas", "dioramacontroller", "dioramaview", "main_showdiorama", "EditorControls", "TrackballControls" %><br>

<%= link_to 'Edit', edit_diorama_path(@diorama) %> |
<%= link_to 'Back', dioramas_path %>