config/routes.rb
Model::Application.routes.draw do
  resources :model_data do
    collection do
      get 'get_contents'
    end
  end
  
  resources :stages do
    collection do
      get 'get_contents'
    end
  end

  resources :dioramas do
    collection do
      post 'ready'
      post 'set_model'
      get 'get_model_datum'
      get 'get_stage'
      get 'get_diorama'
    end
  end

end

app/controllers/model_data_controller.rb
#-*- coding: utf-8 -*-
class ModelDataController < ApplicationController
  before_action :set_model_datum, only: [:show, :edit, :update, :destroy]

  # GET /model_data
  # GET /model_data.json
  def index
    @model_data = ModelDatum.all
  end

  # GET /model_data/1
  # GET /model_data/1.json
  def show
    @data = ActiveSupport::JSON.decode(@model_datum.modeldata)
    @textures = @model_datum.textures
    unless @model_datum.textures.nil?
      @urls = @model_datum.textures.map{ |texture| texture.data.url }
    end
  end

  # GET /model_data/new
  def new
    @model_datum = ModelDatum.new
    @textures = Texture.new
  end

  # GET /model_data/1/edit
  def edit
  end
  
  # POST /model_data
  # POST /model_data.json
  # フォームからファイルを受取り、my_dataフォルダ内に一時保存、
  # JSONファイルにコンバートした後、文字列を抜き出してDBに保存する。
  def create
    # コンバート&モデル作成
    converter = ModelDataService.new()
    @model_datum = converter.convert_model_datum(params)
  
    # saveしてDBへ保存
    respond_to do |format|
      begin
        @model_datum.save!
        format.html { redirect_to @model_datum, notice: 'Model datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @model_datum }
      rescue ActiveRecord::RecordInvalid => e
        puts e
        format.html { render action: 'new' }
        format.json { render json: @model_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_data/1
  # PATCH/PUT /model_data/1.json
  def update
    respond_to do |format|
      if @model_datum.update(model_datum_params)
        format.html { redirect_to @model_datum, notice: 'Model datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @model_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_data/1
  # DELETE /model_data/1.json
  def destroy
    @model_datum.destroy
    respond_to do |format|
      format.html { redirect_to model_data_url }
      format.json { head :no_content }
    end
  end
  
  def get_contents
    model_datum = ModelDatum.find(params[:id])
      
    # If modeldata has at least one texture, set the path
    path = model_datum.textures[0] ? model_datum.textures[0].data.url : ""
    jsonString = { modelData: ActiveSupport::JSON.decode(model_datum.modeldata), texturePath: path }

    render json: jsonString
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_datum
      @model_datum = ModelDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_datum_params
      params.require(:model_datum).permit(:modeldata, :texture, :textures)
    end
    
    def textures_params
      params.require(:textures).permit(:data)
    end
end

app/helpers/model_data_helper.rb
module ModelDataHelper
  def add_texture(form_builder)
    link_to_function "add", :id  => "add_texture" do |page|
      form_builder.fields_for :textures, Texture.new, :child_index => 'NEW_RECORD' do |texture_form|
        html = render(:partial => 'texture', :locals => { :f => texture_form })
        page << "$('add_texture').insert({ before: '#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime()) });"
      end
    end
  end
  def delete_texture(form_builder)
    if form_builder.object.new_record?
      link_to_function("Remove this Texture", "this.up('fieldset').remove()")
    else
      form_builder.hidden_field(:_delete) +
      link_to_function("Remove this Texture", "this.up('fieldset').hide(); $(this).previous().value = '1'")
    end
  end
  
end

app/views/model_data/_form.html.erb
<%= form_for(@model_datum) do |f| %>
  <% if @model_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model_datum.errors.count, "error") %> prohibited this model_datum from being saved:</h2>

      <ul>
      <% @model_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title%><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <p>file</p>
    <%= f.file_field :file %>
  </div>

  <div class="files">
	<%= f.fields_for :texture, html: { class: "upload", multipart: true } do |t| %>
		<%= t.file_field 'model_datum[textures]', multiple: true %>
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/model_data/_texture.html.erb
<fieldset>
    <% if !f.object.new_record? %>
        <%= image_tag f.object.data.url %>
    <% end %>
    
    <%= f.file_field :data %>
    <%= delete_texture(f) %>
</fieldset>

app/views/model_data/edit.html.erb
<h1>Editing model_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @model_datum %> |
<%= link_to 'Back', model_data_path %>

app/views/model_data/index.html.erb
<h1>Listing model_data</h1>

<table>
  <thead>
    <tr>
      <th>Modeldata</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @model_data.each do |model_datum| %>
      <tr>
        <td><%= model_datum.title %></td>
        <td><%= link_to 'Show', model_datum %></td>
        <td><%= link_to 'Edit', edit_model_datum_path(model_datum) %></td>
        <td><%= link_to 'Destroy', model_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td><!---->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model datum', new_model_datum_path %><br>
<%= link_to 'Index of Stage', stages_path %><br>
<%= link_to 'Index of Diorama', dioramas_path %>

app/views/model_data/new.html.erb
<h1>New model_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', model_data_path %>

app/views/model_data/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Modeldata:</strong></p>
<div id="id"><%= @model_datum.id %></div>

<%= javascript_include_tag "stats.min", "TrackballControls", "styledstats", "show_model" %>

<%= link_to 'Edit', edit_model_datum_path(@model_datum) %> |
<%= link_to 'Back', model_data_path %>