config/routes.rb
Model::Application.routes.draw do
  resources :model_data do
    collection do
      get 'get_contents'
    end
  end
  
  resources :stages do
    collection do
      get 'get_contents'
    end
  end

  resources :dioramas do
    collection do
      post 'ready'
      post 'set_model'
      get 'get_model_datum'
      get 'get_stage'
      get 'get_diorama'
    end
  end

end

app/models/stage.rb
class Stage < ActiveRecord::Base  
    has_many :textures, :as => :texturable, :dependent => :destroy
    belongs_to :diorama
    
    accepts_nested_attributes_for :textures, allow_destroy: true
    #accepts_nested_attributes_for :scene_data
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
    @data = ActiveSupport::JSON.decode(@stage.scene_data)
    @textures = @stage.textures
    unless @stage.textures.nil?
      @urls = @stage.textures.map{ |texture| texture.data.url }
    end
  end

  # GET /stages/new
  def new
    @stage = Stage.new
    @textures = Texture.new
  end

  # GET /stages/1/edit
  def edit
    @stage = Stage.find(params[:id])
  end

  # POST /stages
  # POST /stages.json
  def create
    # JSONファイルから文字列を抽出する
    file = params[:stage][:file]

    @jsonstring = file.read
    @stage = Stage.new(scene_data: @jsonstring, title: params[:stage][:title])

    unless params[:stage][:texture].nil?
      params[:stage][:texture][:stage][:textures].each do |f|
        @stage.textures << Texture.new(data: f)
      end
    end

    respond_to do |format|
      begin
        @stage.save!
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stage }
      rescue ActiveRecord::RecordInvalid => e
        format.html { render action: 'new' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    # JSONファイルから文字列を抽出する
    file = params[:stage][:file]
    jsonstring = file.read
    stage_params = { scene_data: jsonstring, title: params[:stage][:title] }
    
    respond_to do |format|
      if @stage.update_attributes(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url }
      format.json { head :no_content }
    end
  end
  
  def get_contents
    stage = Stage.find(params[:id])
      
    # If modeldata has at least one texture, set the path
    path = stage.textures[0] ? stage.textures[0].data.url : ""
    jsonString = { modelData: ActiveSupport::JSON.decode(stage.scene_data), texturePath: path }

    render json: jsonString
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      #params[:stage]
      params.require(:stage).permit(:scene_data, :textures)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(@stage) do |f| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% @stage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title%><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <p>file</p>
    <%= f.file_field :file %>
  </div>
  
  <div class="files">
	<%= f.fields_for :texture, html: { class: "upload", multipart: true } do |t| %>
		<%= t.file_field 'stage[textures]', multiple: true %>
	<% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Listing stages</h1>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
      	<td><%= stage.title %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %><br>
<%= link_to 'Index of ModelData', model_data_path %><br>
<%= link_to 'Index of Diorama', dioramas_path %>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Stagedata:</strong></p>
<div id="id"><%= @stage.id %></div>

<%= javascript_include_tag "stats.min", "TrackballControls", "styledstats", "show_model" %>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>